docs_dir: src
site_name: Watchdog Docs
site_url: https://docs.abls-habitat.fr/
repo_url: https://svn.abls-habitat.fr/repo/Watchdog/prod/
repo_name: Watchdog Repository
site_description: Documentation du projet domotique Watchdog
site_author: Sébastien et Bruno Lefèvre
site_dir: build
extra_css: [extra.css]

nav:

 - Découverte:
   - Tour d'horizon: index.md
   - Galerie: galerie.md
 - Prise en main:
   - Guide de démarrage: guide_demarrage.md
 - Guide de l'utilisateur:
   - Typologie des Utilisateurs: users.md
 - Programmation D.L.S:
   - Le concept: dls.md
   - Les alias: dls_alias.md
   - Les liens: dls_link.md
   - La logique: dls_logique.md
   - Les calculs: dls_calculs.md
   - Les visuels: dls_visuels.md
 - Inventaire des Visuels: visuels.md
 - Pour finir ?:
   - Qui sommes-nous ?: auteurs.md

theme:
 name: readthedocs
 locale: fr
